version: 2.1

orb:
  python: circleci/python@1.0.0

jobs:
  build-and-test:
    excecutor:
      name: python/default
      tag: '3.8'
    steps:
      - checkout
      - run:
          name: Setup Virtual Env
          command: |
            virtualenv -p python3.8 venv
            echo "source ./venv/bin/activate" >> $BASH_ENV
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt

worflows:
  build-test-and-deploy:
      jobs:
        - build-and-test:
          filters:
            branhces:
              only:
              - cicd-demo-dev