version: 2.1

orbs:  
  python: circleci/python@1.0.0
  aws-cli: circleci/aws-cli@1.2.1

jobs:  
  build-and-test:    
    executor:
      name: python/default
      tag: '3.8'
    steps:
      - checkout
      - run:
          name: Setup Virtual venv
          command: |
            virtualenv -p python3.8 venv            
            echo "source ./venv/bin/activate" >> $BASH_ENV
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt
      - run:
          name: Create ENV file
          command: env > .env
      - run:
          name: Test
          command: pytest
      - run:
          name: Create Zipfile archive of Dependencies
          command: |
            cd venv/lib/python3.8/site-packages
            zip -r9 ../../../../function.zip .
      - run:
          name: Add App to Zipfile
          command: zip -g ./function.zip .env -r app
      - persist_to_workspace:
          root: .
          paths:
            - function.zip

  deploy-dev:
    executor: aws-cli/default
    steps:
    - attach_workspace:
        at: ./
    - aws-cli/setup:
        aws-region: AWS_DEFAULT_REGION
        aws-access-key-id: AWS_ACCESS_KEY_ID
        aws-secret-access-key: AWS_SECRET_ACCESS_KEY
    - run:
        name: Upload to S3
        command: aws s3 cp function.zip s3://serverless-ent/function.zip
    - run:
        name: Deploy new Lambda
        command: aws lambda update-function-code --function-name serverless-fastapi --s3-bucket serverless-ent --s3-key function.zip


workflows:  
  build-test-and-deploy:    
    jobs:      
      - build-and-test:
          context: cicd-demo-dev 
          filters:            
            branches:
              only:
                - cicd-demo-dev
      - deploy-dev:
          context: cicd-demo-dev
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - cicd-demo-dev